#ifndef RTE_COMPONENTS_H
#define RTE_COMPONENTS_H

#define CMSIS_device_header "stdint.h"
#define RTE_Acceleration_Arm_2D
#define RTE_Acceleration_Arm_2D_Alpha_Blending
#define RTE_Acceleration_Arm_2D_Helper_PFB
#define RTE_Acceleration_Arm_2D_Helper_Disp_Adapter0
#define RTE_Acceleration_Arm_2D_Extra_LCD_printf

#endif
